Aeyb #41 side bar fixating
UoaWDCC/AEYB pull request #47
Opened 2022-10-02 05:59 UTC by TylerDonghwi

- The files are fixed to increase the maintainability.
- Sidebar is dependent on what page the user is currently on.

2022-10-02 06:23 UTC, luke-mccallum requested changes
Looks good but the sidebar shouldn't show up before the user has logged in

2022-10-02 06:25 UTC, luke-mccallum commented
Additionally, calendar is spelt calengdar on the sidebar, nothing else that I noticed though

2022-10-02 06:28 UTC, TylerDonghwi commented
Yeah I forgot to consider that lmao

2022-10-04 08:30 UTC, luke-mccallum approved these changes

2022-10-04 08:39 UTC, luke-mccallum approved these changes

2022-10-04 08:39 UTC, merged